/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppAbout {
    }
    interface AppRoot {
        "update": () => Promise<void>;
    }
    interface DoremiDetector {
        "addCover": () => Promise<void>;
        "deleteCover": () => Promise<void>;
        "exportImage": () => Promise<Blob>;
        "loading": boolean;
        "showFrame": boolean;
        "src": string;
        "update": () => Promise<void>;
    }
    interface DoremiEditor {
        "addCover": () => Promise<void>;
        "deleteCover": () => Promise<void>;
        "height": number;
        "pid": number;
        "setData": (data: any) => Promise<void>;
        "update": () => Promise<void>;
        "width": number;
    }
}
declare global {
    interface HTMLAppAboutElement extends Components.AppAbout, HTMLStencilElement {
    }
    var HTMLAppAboutElement: {
        prototype: HTMLAppAboutElement;
        new (): HTMLAppAboutElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLDoremiDetectorElement extends Components.DoremiDetector, HTMLStencilElement {
    }
    var HTMLDoremiDetectorElement: {
        prototype: HTMLDoremiDetectorElement;
        new (): HTMLDoremiDetectorElement;
    };
    interface HTMLDoremiEditorElement extends Components.DoremiEditor, HTMLStencilElement {
    }
    var HTMLDoremiEditorElement: {
        prototype: HTMLDoremiEditorElement;
        new (): HTMLDoremiEditorElement;
    };
    interface HTMLElementTagNameMap {
        "app-about": HTMLAppAboutElement;
        "app-root": HTMLAppRootElement;
        "doremi-detector": HTMLDoremiDetectorElement;
        "doremi-editor": HTMLDoremiEditorElement;
    }
}
declare namespace LocalJSX {
    interface AppAbout {
    }
    interface AppRoot {
    }
    interface DoremiDetector {
        "loading"?: boolean;
        /**
          * Emitted when an error occurred.
         */
        "onDetectorError"?: (event: CustomEvent<any>) => void;
        /**
          * Emitted when loading changes.
         */
        "onLoadingChange"?: (event: CustomEvent<any>) => void;
        /**
          * Emitted when show-frame changes.
         */
        "onShowFrameChange"?: (event: CustomEvent<any>) => void;
        /**
          * Emitted when src changes.
         */
        "onSrcChange"?: (event: CustomEvent<any>) => void;
        "showFrame"?: boolean;
        "src"?: string;
    }
    interface DoremiEditor {
        "height"?: number;
        "pid"?: number;
        "width"?: number;
    }
    interface IntrinsicElements {
        "app-about": AppAbout;
        "app-root": AppRoot;
        "doremi-detector": DoremiDetector;
        "doremi-editor": DoremiEditor;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-about": LocalJSX.AppAbout & JSXBase.HTMLAttributes<HTMLAppAboutElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "doremi-detector": LocalJSX.DoremiDetector & JSXBase.HTMLAttributes<HTMLDoremiDetectorElement>;
            "doremi-editor": LocalJSX.DoremiEditor & JSXBase.HTMLAttributes<HTMLDoremiEditorElement>;
        }
    }
}
